# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        node-version: '20.x'
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-html flake8 flake8-html
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run tests
      run: |
        pytest --html=pytest_report.html

    - name: Run linter
      run: |
        # Generate HTML report
        flake8 --format=html --htmldir=flake-report 
        
    - name: Commit and push reports
      uses: EndBug/add-and-commit@v7
      with:
        add: 'pytest_report.html, flake-report'
        message: 'Add test and linting reports'
        author_name: ${{ github.actor }}
        author_email: ${{ github.actor }}@users.noreply.github.com

    - name: Push changes
      uses: ad-m/github-push-action@v0.7.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: develop
